FROM ghcr.io/gleam-lang/gleam:v1.17.0-node-alpine

WORKDIR /app

RUN apk update && apk add --no-cache inotify-tools erlang erlang-dev rebar3

COPY gleam.toml manifest.toml package*.json ./ 

RUN chown -R node:node /app

USER node

RUN npm install

RUN if [ -f gleam.toml ]; then gleam deps download; fi

COPY . .
