services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      # Dockerfile の ARG にホストのUID/GIDを渡す
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    # user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "1234:1234"
    volumes:
      - .:/app
      - /app/node_modules
