input {
    file {
        path => "/var/log/app/application.log"
        start_position => "beginning"
        sincedb_path => "/tmp/logstash.sincedb"
    }
}

output {
    stdout {
        codec => rubydebug
    }

    elasticsearch {
        hosts => ["https://elasticsearch:9200"]
        index => "online-workspace-%{+yyyy.MM.dd}"
        user => "elastic"
        password => "${ELASTIC_PASSWORD}"
        ssl_enabled => true
        ssl_verification_mode => "none"
    }
}

