services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.5.1
    environment:
      discovery.type: single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:9.5.1
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    volumes:
      - ./docker/elk/logstash/pipeline:/usr/share/logstash/pipeline:ro
      - app_logs:/var/log/app:ro
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:9.5.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
