server {
    listen 80;
    server_name _;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    location /api/ {
        proxy_pass http://backend:8080;
    }

    location /ws {
        proxy_pass http://backend:8080;
    }

    location / {
        proxy_pass http://frontend:5173;
    }

    # 以下テスト用
    # Lustre ホットリロード専用
    location /.lustre/ {
        proxy_pass http://frontend:5173;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    # モックサーバー
    location /ws-test {
        proxy_pass http://ws-mock:8081;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }
}
