DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS room_members;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS account_statuses;

CREATE TABLE account_statuses (
    id SMALLINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    account_status_id SMALLINT NOT NULL REFERENCES account_statuses(id),
    suspended_until TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users(id),
    icon_url VARCHAR(500)
);

CREATE TABLE rooms (
    id BIGINT PRIMARY KEY
);

CREATE TABLE room_members (
    id BIGINT PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    left_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    content VARCHAR(500) NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO account_statuses VALUES (1, 'ACTIVE'), (2, 'SUSPENDED');
INSERT INTO users VALUES
    (1, '参加者', 'member@example.com', 'hash', 1, NULL, NULL),
    (2, '参加者2', 'member2@example.com', 'hash', 1, NULL, NULL),
    (3, '部外者', 'outsider@example.com', 'hash', 1, NULL, NULL),
    (4, '停止中', 'suspended@example.com', 'hash', 2, NULL, NULL);
INSERT INTO profiles VALUES (1, 'https://example.com/member.png');
INSERT INTO rooms VALUES (10), (20);
INSERT INTO room_members VALUES
    (1, 10, 1, NULL),
    (2, 10, 2, NULL),
    (3, 10, 3, TIMESTAMP WITH TIME ZONE '2026-08-29 00:00:00+00');
INSERT INTO messages (id, room_id, user_id, content, sent_at) VALUES
    (100, 10, 1, '古いメッセージ', TIMESTAMP WITH TIME ZONE '2026-08-29 00:00:00+00'),
    (101, 10, 2, '新しいメッセージ', TIMESTAMP WITH TIME ZONE '2026-08-30 00:00:00+00');
