DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS room_categories;
DROP TABLE IF EXISTS room_category_statuses;

CREATE TABLE room_category_statuses (
    id SMALLINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO room_category_statuses (id, code) VALUES (1, 'ACTIVE'), (2, 'INACTIVE');

CREATE TABLE room_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500) NOT NULL DEFAULT '',
    status_id SMALLINT NOT NULL DEFAULT 1 REFERENCES room_category_statuses(id),
    sort_order INT NOT NULL DEFAULT 0
);

CREATE TABLE profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    icon_url VARCHAR(500),
    bio VARCHAR(500) NOT NULL DEFAULT '',
    work_category_id BIGINT REFERENCES room_categories(id),
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DELETE FROM users WHERE email LIKE 'profile-%@example.com';
