DROP TABLE IF EXISTS work_sessions;
DROP TABLE IF EXISTS blocks;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS friend_statuses;
DROP TABLE IF EXISTS room_members;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS room_statuses;
DROP TABLE IF EXISTS visibilities;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE profiles (
    user_id BIGINT PRIMARY KEY,
    icon_url VARCHAR(500)
);

CREATE TABLE visibilities (
    id SMALLINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE room_statuses (
    id SMALLINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE friend_statuses (
    id SMALLINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE rooms (
    id BIGINT PRIMARY KEY,
    created_by BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    max_members SMALLINT NOT NULL,
    visibility_id SMALLINT NOT NULL,
    status_id SMALLINT NOT NULL
);

CREATE TABLE room_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL,
    left_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE friends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    friend_user_id BIGINT NOT NULL,
    status_id SMALLINT NOT NULL
);

CREATE TABLE blocks (
    blocker_user_id BIGINT NOT NULL,
    blocked_user_id BIGINT NOT NULL,
    PRIMARY KEY (blocker_user_id, blocked_user_id)
);

CREATE TABLE work_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (id, name, email) VALUES
    (1, 'creator', 'creator@example.com'),
    (2, 'member', 'member@example.com'),
    (3, 'other', 'other@example.com');

INSERT INTO profiles (user_id, icon_url) VALUES
    (1, NULL),
    (2, 'https://example.com/member.png'),
    (3, NULL);

INSERT INTO visibilities (id, code) VALUES
    (1, 'PUBLIC'),
    (3, 'FRIENDS_ONLY');

INSERT INTO room_statuses (id, code) VALUES
    (1, 'OPEN'),
    (2, 'CLOSED');

INSERT INTO friend_statuses (id, code) VALUES
    (1, 'ACTIVE'),
    (2, 'REMOVED');

INSERT INTO rooms (id, created_by, category_id, max_members, visibility_id, status_id) VALUES
    (10, 1, 100, 3, 1, 1),
    (11, 1, 100, 3, 3, 1),
    (13, 1, 100, 2, 1, 1),
    (14, 1, 100, 3, 1, 1),
    (15, 1, 100, 3, 1, 2);

INSERT INTO room_members (room_id, user_id, joined_at) VALUES
    (10, 1, '2026-08-15T00:00:00Z'),
    (11, 1, '2026-08-15T00:00:00Z'),
    (13, 1, '2026-08-15T00:00:00Z'),
    (13, 3, '2026-08-15T00:00:00Z'),
    (14, 1, '2026-08-15T00:00:00Z');

INSERT INTO friends (user_id, friend_user_id, status_id)
VALUES (1, 2, 1);
