DROP ALL OBJECTS;

CREATE TABLE room_category_statuses (
    id SMALLINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE work_styles (
    id SMALLINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE room_statuses (
    id SMALLINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE room_categories (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500) NOT NULL DEFAULT '',
    status_id SMALLINT NOT NULL REFERENCES room_category_statuses(id),
    sort_order INT NOT NULL DEFAULT 0
);

CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    icon_url VARCHAR(500)
);

CREATE TABLE rooms (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    created_by BIGINT NOT NULL REFERENCES users(id),
    category_id BIGINT NOT NULL REFERENCES room_categories(id),
    work_style_id SMALLINT NOT NULL REFERENCES work_styles(id),
    max_members SMALLINT NOT NULL CHECK (max_members BETWEEN 2 AND 12),
    status_id SMALLINT NOT NULL DEFAULT 1 REFERENCES room_statuses(id),
    closed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE room_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMP WITH TIME ZONE
);

INSERT INTO room_category_statuses (id, code) VALUES (1, 'ACTIVE'), (2, 'INACTIVE');
INSERT INTO work_styles (id, code) VALUES (1, 'FOCUS'), (2, 'CHAT_OK');
INSERT INTO room_statuses (id, code) VALUES (1, 'OPEN'), (2, 'CLOSED');

INSERT INTO users (id, name, email) VALUES
    (1, '作成者', 'creator@example.com'),
    (2, '参加者', 'member@example.com'),
    (3, '閲覧者', 'viewer@example.com');

INSERT INTO profiles (user_id, icon_url) VALUES
    (1, 'https://example.com/creator.png'),
    (2, 'https://example.com/member.png');

INSERT INTO room_categories (id, name, description, status_id, sort_order) VALUES
    (1, '開発', 'ソフトウェア開発', 1, 10),
    (2, '読書', '読書会', 1, 20),
    (3, '停止中', '利用できないカテゴリ', 2, 30);

INSERT INTO rooms (id, name, description, created_by, category_id, work_style_id, max_members, status_id) VALUES
    (10, '参加可能', '説明', 1, 1, 1, 3, 1),
    (11, '終了済み', '説明', 1, 1, 1, 3, 2);

INSERT INTO room_members (room_id, user_id, left_at) VALUES
    (10, 1, NULL),
    (10, 2, NULL),
    (10, 3, NULL),
    (11, 1, NULL);
