DROP TABLE IF EXISTS room_members;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS room_categories;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS room_statuses;
DROP TABLE IF EXISTS work_styles;
DROP TABLE IF EXISTS room_category_statuses;

CREATE TABLE room_category_statuses (
    id SMALLINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE work_styles (
    id SMALLINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE room_statuses (
    id SMALLINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE room_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500) NOT NULL DEFAULT '',
    status_id SMALLINT NOT NULL REFERENCES room_category_statuses(id),
    sort_order INT NOT NULL DEFAULT 0
);

CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    icon_url VARCHAR(500)
);

CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    created_by BIGINT NOT NULL REFERENCES users(id),
    category_id BIGINT NOT NULL REFERENCES room_categories(id),
    work_style_id SMALLINT NOT NULL REFERENCES work_styles(id),
    max_members SMALLINT NOT NULL CHECK (max_members BETWEEN 2 AND 12),
    status_id SMALLINT NOT NULL DEFAULT 1 REFERENCES room_statuses(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE room_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMP WITH TIME ZONE
);

INSERT INTO room_category_statuses (id, code) VALUES (1, 'ACTIVE'), (2, 'INACTIVE');
INSERT INTO work_styles (id, code) VALUES (1, 'FOCUS'), (2, 'CHAT_OK');
INSERT INTO room_statuses (id, code) VALUES (1, 'OPEN'), (2, 'CLOSED');
INSERT INTO users (id, name, email) VALUES (1, '作成者', 'creator@example.com');
INSERT INTO profiles (user_id, icon_url) VALUES (1, 'https://example.com/creator.png');
INSERT INTO room_categories (id, name, description, status_id, sort_order) VALUES
    (1, '開発', 'ソフトウェア開発', 1, 10),
    (2, '停止中', '利用できないカテゴリ', 2, 20);
