DROP TABLE IF EXISTS room_members;
DROP TABLE IF EXISTS room_invites;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS account_statuses;
DROP TABLE IF EXISTS room_statuses;

CREATE TABLE account_statuses (
    id SMALLINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE room_statuses (
    id SMALLINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    account_status_id SMALLINT NOT NULL,
    suspended_until TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE rooms (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    max_members SMALLINT NOT NULL,
    status_id SMALLINT NOT NULL
);

CREATE TABLE room_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    icon_url VARCHAR(500)
);

CREATE TABLE room_invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    invalidated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO account_statuses (id, code) VALUES (1, 'ACTIVE'), (2, 'SUSPENDED');
INSERT INTO room_statuses (id, code) VALUES (1, 'OPEN'), (2, 'CLOSED');
INSERT INTO users (id, name, email, password_hash, account_status_id, suspended_until, deleted_at) VALUES
    (1, '作成者', 'creator@example.com', 'x', 1, NULL, NULL),
    (2, '参加者', 'member@example.com', 'x', 1, NULL, NULL),
    (3, '閲覧者', 'viewer@example.com', 'x', 1, NULL, NULL);
INSERT INTO profiles (user_id, icon_url) VALUES
    (1, 'https://example.com/creator.png'),
    (2, 'https://example.com/member.png'),
    (3, 'https://example.com/viewer.png');
INSERT INTO rooms (id, name, max_members, status_id) VALUES
    (10, '招待ルーム', 3, 1),
    (11, '終了済みルーム', 3, 2);
INSERT INTO room_members (room_id, user_id, left_at) VALUES
    (10, 1, NULL);
INSERT INTO room_invites (room_id, created_by, token, expires_at, invalidated_at) VALUES
    (10, 1, 'validtoken', TIMESTAMP WITH TIME ZONE '2099-01-01 00:00:00+00', NULL),
    (10, 1, 'expiredtoken', TIMESTAMP WITH TIME ZONE '2000-01-01 00:00:00+00', NULL);
