global:
  scrape_interval: 15s

scrape_configs:
  - job_name: online-workspace
    metrics_path: /metrics
    http_headers:
      X-API-Key:
        files:
          - /run/secrets/management_api_key
    static_configs:
      - targets:
          - backend:8080
