apiVersion: 1

contactPoints:
  - orgId: 1
    name: Online Workspace Discord
    receivers:
      - uid: online-workspace-discord
        type: discord
        settings:
          url: $GRAFANA_ALERT_DISCORD_WEBHOOK_URL
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: Online Workspace Discord
    group_by:
      - grafana_folder
      - alertname
