apiVersion: 1

groups:
  - orgId: 1
    name: Online Workspace
    folder: Online Workspace
    interval: 1m
    rules:
      - uid: online-workspace-high-5xx-rate
        title: API 5xx率が高い
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: 100 * sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) / clamp_min(sum(rate(http_server_requests_seconds_count[5m])), 0.000000001)
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              type: reduce
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 5
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        dashboardUid: online-workspace-monitoring
        panelId: 2
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          __dashboardUid__: online-workspace-monitoring
          __panelId__: "2"
          description: 直近5分のAPIリクエストに占める5xxレスポンスの割合が5%を超えています。
          summary: APIの5xxエラー率が高騰しています
        labels:
          severity: warning
        isPaused: false
